name: Checkov

on:
    pull_request:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# These permissions are needed to interact with GitHub's OIDC Token endpoint and
# for github/codeql-action/upload-sarif to upload SARIF results.
permissions:
    id-token: write
    contents: read
    pull-requests: write
    security-events: write
    actions: read

jobs: 
    checkov:
        name: "checkov"

        uses: g13z/gha-workflows/.github/workflows/checkov.yml@a55934a54e886968355d08adfa7910242c3c8780 # v1.1.0
