name: Terraform Plan

on:
    pull_request:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs: 
    plan:
        name: "Plan"

        uses: rewindio/github-action-terraform-aws/.github/workflows/plan.yml@v1
        with:
            region: us-east-1
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
