name: Terraform Plan

on:
    pull_request:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs: 
    plan:
        name: "Plan"

        uses: g13z/gha-workflows/.github/workflows/plan.yml@b8a393a06d7985460d3c2612c6ec86873fc09fc9 # v1.0.0
        with:
            region: us-east-1
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
